# Generated by Django 3.2.5 on 2021-10-02 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0002_alter_pokemon_pokemon_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ataque',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='ataque',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ataque',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='ataque',
            field=models.ManyToManyField(related_name='ataque', to='AppCatalogo.Ataque'),
        ),
    ]
