# Generated by Django 3.2.5 on 2021-10-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0004_alter_pokemon_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='ataque',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ataques',
            field=models.ManyToManyField(to='AppCatalogo.Ataque', verbose_name='ataque'),
        ),
    ]
