# Generated by Django 3.2.5 on 2021-10-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0005_auto_20211002_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mezcla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('ataque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCatalogo.ataque')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCatalogo.pokemon')),
            ],
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='ataques',
            field=models.ManyToManyField(through='AppCatalogo.Mezcla', to='AppCatalogo.Ataque'),
        ),
    ]
