# Generated by Django 3.2.5 on 2021-10-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0006_auto_20211002_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mezcla',
            name='date_joined',
        ),
    ]
