# Generated by Django 3.2.5 on 2021-10-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0007_remove_mezcla_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezcla',
            name='date_joined',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
