# Generated by Django 3.2.5 on 2021-10-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0008_mezcla_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezcla',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
