# Generated by Django 3.2.5 on 2021-10-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0009_alter_mezcla_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezcla',
            name='date_joined',
            field=models.DateTimeField(),
        ),
    ]
