# Generated by Django 3.2.5 on 2021-10-03 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0010_alter_mezcla_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ataque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCatalogo.ataque')),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='ataques',
        ),
        migrations.DeleteModel(
            name='Mezcla',
        ),
        migrations.AddField(
            model_name='union',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCatalogo.pokemon'),
        ),
    ]
