# Generated by Django 3.2.5 on 2021-10-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0011_auto_20211002_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='ataques',
            field=models.ManyToManyField(through='AppCatalogo.Union', to='AppCatalogo.Ataque'),
        ),
    ]
