# Generated by Django 3.2.5 on 2021-10-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0012_pokemon_ataques'),
    ]

    operations = [
        migrations.AddField(
            model_name='union',
            name='created',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
