# Generated by Django 3.2.5 on 2021-10-03 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0013_union_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='ataques',
        ),
        migrations.RemoveField(
            model_name='union',
            name='created',
        ),
    ]
