# Generated by Django 3.2.5 on 2021-10-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0018_remove_pokemon_ataques'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='ataques',
            field=models.ManyToManyField(through='AppCatalogo.Mezcla', to='AppCatalogo.Ataque'),
        ),
    ]
