# Generated by Django 3.2.5 on 2021-10-03 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0019_pokemon_ataques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='ataques',
        ),
    ]
