# Generated by Django 3.2.5 on 2021-10-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0022_pokemon_ataques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mezcla',
            name='created',
        ),
    ]
