# Generated by Django 3.2.5 on 2021-10-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0023_remove_mezcla_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='ataques',
            field=models.ManyToManyField(to='AppCatalogo.Ataque'),
        ),
        migrations.DeleteModel(
            name='Mezcla',
        ),
    ]
