# Generated by Django 3.2.5 on 2021-10-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0026_alter_pokemon_ataques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='ataques',
            field=models.ManyToManyField(to='AppCatalogo.Ataque', verbose_name='ataques anidados!!!'),
        ),
    ]
