# Generated by Django 3.2.5 on 2021-10-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0027_alter_pokemon_ataques'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ataque',
            options={'ordering': ['attack_name']},
        ),
    ]
