# Generated by Django 3.2.5 on 2021-10-06 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0029_alter_pokemon_ataques'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonAtaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('ataque_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCatalogo.ataque')),
                ('pokemon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCatalogo.pokemon')),
            ],
        ),
    ]
