# Generated by Django 3.2.5 on 2021-10-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCatalogo', '0030_pokemonataque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='ataques',
        ),
    ]
