# Generated by Django 3.2.5 on 2021-10-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppPrincipal', '0004_auto_20211014_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ataques', models.ManyToManyField(to='AppPrincipal.Ataque', verbose_name='ataques')),
                ('pokemones', models.ManyToManyField(to='AppPrincipal.Pokemon', verbose_name='pokemones')),
            ],
        ),
        migrations.CreateModel(
            name='Gary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ataques', models.ManyToManyField(to='AppPrincipal.Ataque', verbose_name='ataques')),
                ('pokemones', models.ManyToManyField(to='AppPrincipal.Pokemon', verbose_name='pokemones')),
            ],
        ),
        migrations.CreateModel(
            name='Fabiola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ataques', models.ManyToManyField(to='AppPrincipal.Ataque', verbose_name='ataques')),
                ('pokemones', models.ManyToManyField(to='AppPrincipal.Pokemon', verbose_name='pokemones')),
            ],
        ),
        migrations.CreateModel(
            name='Daniel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ataques', models.ManyToManyField(to='AppPrincipal.Ataque', verbose_name='ataques')),
                ('pokemones', models.ManyToManyField(to='AppPrincipal.Pokemon', verbose_name='pokemones')),
            ],
        ),
        migrations.CreateModel(
            name='Aghata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ataques', models.ManyToManyField(to='AppPrincipal.Ataque', verbose_name='ataques')),
                ('pokemones', models.ManyToManyField(to='AppPrincipal.Pokemon', verbose_name='pokemones')),
            ],
        ),
    ]
