# Generated by Django 3.2.5 on 2021-10-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='ataques',
            field=models.ManyToManyField(to='AppPrincipal.Ataque'),
        ),
    ]
