# Generated by Django 3.2.5 on 2021-10-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPrincipal', '0002_pokemon_ataques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='ataques',
            field=models.ManyToManyField(to='AppPrincipal.Ataque', verbose_name='ataques'),
        ),
    ]
