# Generated by Django 3.2.5 on 2021-10-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPortada', '0002_pokemon_ataques'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_life',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='ataques',
            field=models.ManyToManyField(to='AppPortada.Ataque'),
        ),
        migrations.DeleteModel(
            name='PokemonAtaque',
        ),
    ]
